stages:
  - build
  - push
  - deploy

build:
  stage: build
  image: cr.yandex/yc/metadata-token-docker-helper:0.2
  services:
    - docker:19.03.1-dind
  script:
    - docker build . -t cr.yandex/crp5ktme2guoak76mnk2/myapp:gitlab-$CI_COMMIT_SHORT_SHA

push:
  stage: push
  image: cr.yandex/yc/metadata-token-docker-helper:0.2
  services:
    - docker:19.03.1-dind
  script:
    - docker push cr.yandex/crp5ktme2guoak76mnk2/myapp:gitlab-$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  script:
    - sed -i "s/__VERSION__/gitlab-$CI_COMMIT_SHORT_SHA/" deployment.yaml    
    - kubectl apply -f deployment.yaml
    - kubectl apply -f service.yaml
    - kubectl apply -f ingress-myapp.yaml