---
  - name: Kubeadm init
    shell: kubeadm init --node-name=master.sarajkins.space --apiserver-cert-extra-sans=master --pod-network-cidr 10.244.0.0/16

  - name: Copy config to home directory
    shell: mkdir -p /home/ubuntu/.kube && sudo cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config && sudo chown -R ubuntu:ubuntu /home/ubuntu/.kube

  - name: Copy config to home directory
    shell: mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config

#  - name: Copy config to localhost
#    fetch: 
#      src: /home/ubuntu/.kube/config
#      dest: $HOME/.kube

  - name: Download CNI plugin
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

  - name: Kubeadm token print
    shell: kubeadm token create --print-join-command
