---
#- hosts: srv-worker
#  tasks:
#  - name: Join node
#    shell: kubeadm join 192.168.101.35:6443 --token gk7b1v.sgizmg868vjor74q --discovery-token-ca-cert-hash sha256:4598aead2ce917a61997b9093e7b27d22a6ffd6711a6df22f5f0f154ba7d819b
#    shell: kubeadm join 158.160.56.147:6443
#    shell: kubeadm join --skip-phases=preflight 10.0.90.30:6443
- hosts: srv-cp
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: srv-worker
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt