---
- hosts: master worker01 worker02
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add kubernetes apt-key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Add kubernetes apt repository
    apt_repository:
      repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
      state: present
      filename: kubernetes


  - name: Install Kubernetes packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl

  - name: Fix settings
    shell: echo 1 > /proc/sys/net/ipv4/ip_forward && modprobe br_netfilter

  - name: Install containerd
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

#  - name: Add containerd apt-key
#    apt_key:
#      url: https://download.docker.com/linux/ubuntu/gpg
#      state: present

  - name: Install containerd
    shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list

#  - name: Add containerd apt repository
#    apt_repository:
#      repo: 'https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
#      state: present
#      filename: containerd

  - name: Install containerd
    shell: apt-get update -y
  
  - name: Install containerd
    shell: apt-get install containerd.io -y

  - name: Fix containerd
    shell: rm /etc/containerd/config.toml

  - name: Fix containerd
    shell: systemctl restart containerd