- name: deploy
  hosts: localhost
  connection: local

  tasks:

  - name: make infrastructure
    shell: cd ../terraform && terraform apply --auto-approve

  - name: get output
    shell: cd ../terraform && sleep 60 && terraform output -json > output.json 

  - name: create 'hosts'
    shell: cd ../terraform && sleep 1 && ./hosts.sh 

  - name: deploy
    shell: ansible-playbook playbooks/setup-all.yaml -i inventory/hosts -b -v
